services:
  db:
    image: mysql:8.4
    container_name: test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quiz
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
